<Button>:
    font_size: 20
    color: 0,1,0,1
    size_hint: 0.4,0.2


FloatLayout:
    Label:
        text: 'HOME'
        font_size: 32
        pos_hint: {"y":0.32}

    Button:
        text: "Form"
        pos_hint: {"x":0.07, "y":0.45, "left":0.07}

    Button:
        text:"Search"
        pos_hint: {"x":0.53, "y":0.45, "left":0.53}

    Button:
        text:"Exit"
        color: 1,0,0,1
        size_hint: 0.2,0.1
        pos_hint: {"x":.4, "y":.12, "left":.4}